server:
  port: 8080

spring:
  application:
    name: zanata-server-spring
    version: @project.version@

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

  datasource:
    url: ${ZANATA_DB_URL:jdbc:postgresql://localhost:5432/zanata?options=-c%20TimeZone%3DUTC}
    username: ${ZANATA_DB_USER:postgres}
    password: ${ZANATA_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jpa.compliance.query: false

vaadin:
  allowed-packages: com.vaadin,com.vaadin.componentfactory,org.vaadin,de.f0rce,org.zanata.spring.vaadin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
