server:
  port: ${VERBARIA_PORT:8080}

spring:
  application:
    name: zanata-server-spring
    version: @project.version@

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

  datasource:
    url: jdbc:postgresql://${VERBARIA_DB_HOST:localhost}:${VERBARIA_DB_PORT:5432}/${VERBARIA_DB_NAME:verbaria}?${VERBARIA_DB_OPTIONS:}
    username: ${VERBARIA_DB_USER:postgres}
    password: ${VERBARIA_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: ${VERBARIA_TIMEZONE:UTC}
      hibernate.jpa.compliance.query: false

vaadin:
  allowed-packages: com.vaadin,com.vaadin.componentfactory,org.vaadin,de.f0rce,org.verbaria.server.ui

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
